# Generated by Django 6.0.3 on 2026-05-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('CodigoCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Precio', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Descripcion', models.TextField(max_length=200)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='App.categoria')),
            ],
        ),
    ]
