# Generated by Django 6.0.3 on 2026-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunkoPop',
            fields=[
                ('CodigoFunko', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('SerieAnime', models.CharField(max_length=100)),
                ('Personaje', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
